version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "DTrombett"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
        update-types: ["security"]
