DROP TABLE IF EXISTS Predictions;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Reminders;
CREATE TABLE Users (
	id VARCHAR(31) PRIMARY KEY,
	dayPoints INTEGER,
	match INTEGER,
	remindMinutes INTEGER,
	reminded INTEGER DEFAULT 0,
	matchPointsHistory VARCHAR(255)
);
CREATE TABLE Predictions (
	matchId INTEGER NOT NULL,
	userId VARCHAR(31) NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	prediction VARCHAR(255) NOT NULL,
	PRIMARY KEY (userId, matchId)
);
CREATE TABLE Reminders (
	date VARCHAR(255) NOT NULL,
	userId VARCHAR(31) NOT NULL,
	remind VARCHAR(1023) NOT NULL,
	PRIMARY KEY (date, userId)
);