DROP TABLE IF EXISTS MatchDays;
DROP TABLE IF EXISTS Matches;
DROP TABLE IF EXISTS Predictions;
DROP TABLE IF EXISTS Users;
CREATE TABLE MatchDays (
	day INTEGER PRIMARY KEY,
	categoryId INTEGER NOT NULL,
	startDate DATETIME NOT NULL
);
CREATE TABLE Users (
	id VARCHAR(31) PRIMARY KEY,
	dayPoints INTEGER,
	matchPointsHistory VARCHAR(255)
);
CREATE TABLE Predictions (
	matchId INTEGER NOT NULL,
	userId VARCHAR(31) NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	prediction VARCHAR(255) NOT NULL,
	PRIMARY KEY (userId, matchId)
);