name = "ms-bot"
main = "./src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "KV", id = "0f620c8b0c9e4b0786b894509f82e5d9" }
]
workers_dev = false
upload_source_maps = true

[observability]
enabled = true

[vars]
SEASON_ID = "264681"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "8a298455-ac11-4e0c-b160-4db807cf3572"