name = "ms-bot"
main = "./dist/index.js"
compatibility_date = "2024-01-01"
node_compat = true
kv_namespaces = [
    { binding = "KV", id = "0f620c8b0c9e4b0786b894509f82e5d9" }
]

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "8a298455-ac11-4e0c-b160-4db807cf3572"

[vars]
SEASON_ID = "264681"