export type Player = {
	club: PlayerClub;
	isQualifiedFromChampionshipChallenge: boolean;
	"3vs3Victories": number;
	icon: PlayerIcon;
	tag: string;
	name: string;
	trophies: number;
	expLevel: number;
	expPoints: number;
	highestTrophies: number;
	soloVictories: number;
	duoVictories: number;
	bestRoboRumbleTime: number;
	bestTimeAsBigBrawler: number;
	brawlers: BrawlerStatList;
	nameColor: string;
};
export type PlayerClub = { tag: string; name: string };
export type PlayerIcon = { id: number };
export type BrawlerStatList = BrawlerStat[];
export type BrawlerStat = {
	gadgets: AccessoryList;
	starPowers: StarPowerList;
	id: number;
	rank: number;
	trophies: number;
	highestTrophies: number;
	power: number;
	gears: GearStatList;
	name: JsonLocalizedName;
};
export type AccessoryList = Accessory[];
export type Accessory = { id: number; name: JsonLocalizedName };
export type JsonLocalizedName = string;
export type StarPowerList = StarPower[];
export type StarPower = { id: number; name: JsonLocalizedName };
export type GearStatList = GearStat[];
export type GearStat = { id: number; name: JsonLocalizedName; level: number };
