export const flagEmojis: Record<string, string | undefined> = {
	POL: ":flag_pl:",
	POR: ":flag_pt:",
	ROU: ":flag_ro:",
	SCO: ":scotland:",
	ESP: ":flag_es:",
	SUI: ":flag_ch:",
	ALB: ":flag_al:",
	TUR: ":flag_tr:",
	AUT: ":flag_at:",
	BEL: ":flag_be:",
	SRB: ":flag_rs:",
	DEN: ":flag_dk:",
	ENG: ":england:",
	FRA: ":flag_fr:",
	GER: ":flag_de:",
	CRO: ":flag_hr:",
	HUN: ":flag_hu:",
	ITA: ":flag_it:",
	GEO: ":flag_ge:",
	SVN: ":flag_si:",
	UKR: ":flag_ua:",
	SVK: ":flag_sk:",
	CZE: ":flag_cz:",
	NED: ":flag_nl:",
};
